# Introduction to Pandas

Pandas documentation: http://pandas.pydata.org/pandas-docs/stable/ (homepage: https://pandas.pydata.org/)

Notes from Chapter 3 of https://jakevdp.github.io/PythonDataScienceHandbook/

In [3]:
import numpy as np
import pandas as pd
np.__version__, pd.__version__

('1.14.0', '0.22.0')

In [7]:
# show
def show(data, show_data = 0):
    print (" Index: {:}".format(data.index))
    print (" Shape: {:}".format(data.shape))
    if show_data:
        print(data.values)

## Pandas Series Objects

In [8]:
# Create a Pandas Series object - uses the default index
d1 = pd.Series([0.25, 0.5, 0.75, 1.0])
show(d1, 1)
d1

 Index: RangeIndex(start=0, stop=4, step=1)
 Shape: (4,)
[0.25 0.5  0.75 1.  ]


0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [9]:
# Series as generalized NumPy arrays
# Create the Series with the specfied index values
d2 = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
show(d2, 1)
d2

 Index: Index(['a', 'b', 'c', 'd'], dtype='object')
 Shape: (4,)
[0.25 0.5  0.75 1.  ]


a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
d1[3]

In [ ]:
d1[1:3]

In [ ]:
d2['a']

In [ ]:
d2['b':'d']

In [11]:
# Creating a Series from a dictionary.  Note that that Pandas object sorts
# the series using the dictionary key sort order.
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
show(population, 1)
population

 Index: Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')
 Shape: (5,)
[38332521 19552860 12882135 19651127 26448193]


California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [12]:
# Looks like a dictionary ....
population['Illinois']

12882135

In [ ]:
# but with list-like slicing
population['Illinois':'Texas']

In [ ]:
# along with "regular" slicing
population[2:5]

In [16]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
show(area,1)
area

 Index: Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')
 Shape: (5,)
[423967 170312 149995 141297 695662]


California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

## Pandas DataFrame Objects

In [17]:
states = pd.DataFrame({'population': population,'area': area})
show(states,1)
states

 Index: Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')
 Shape: (5, 2)
[[  423967 38332521]
 [  170312 19552860]
 [  149995 12882135]
 [  141297 19651127]
 [  695662 26448193]]


area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [28]:
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [22]:
states.columns

Index(['area', 'population'], dtype='object')

In [23]:
states['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [26]:
type(states), type(states['area'])

(pandas.core.frame.DataFrame, pandas.core.series.Series)

## Pandas Index Objects

In [18]:
ind1 = states.index
ind1

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [19]:
ind1[2:]

Index(['Illinois', 'New York', 'Texas'], dtype='object')

In [20]:
ind1[-2:]

Index(['New York', 'Texas'], dtype='object')

In [21]:
ind1[::2]

Index(['California', 'Illinois', 'Texas'], dtype='object')

In [29]:
# Set operations -- union, intersection, etc.
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [30]:
indA & indB  # intersection

Int64Index([3, 5, 7], dtype='int64')

In [31]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [32]:
indA ^ indB  # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

## Indexers - loc, iloc, ix

In [33]:
# Consider this example
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [34]:
# Explicit index - note that with a zero-based indexing, we 
# would expect the second element of the list.
data[1]

'a'

In [35]:
# Implicit indexing when slicing - now we get the second and third 
# elements.
data[1:3]

3    b
5    c
dtype: object

In [38]:
# loc - always uses the explicit index 
data.loc[1]

'a'

In [39]:
data.loc[1:3]

1    a
3    b
dtype: object

In [40]:
# iloc - always uses the implicit Python-style index
data.iloc[1]

'b'

In [41]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [42]:
# ix - hybrid - Note the deprecation warning.
data.ix[1]

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


'a'

In [43]:
data.ix[1:3]

1    a
3    b
dtype: object

## Data selection in a DataFrame

In [44]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [46]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [47]:
data.area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [48]:
# Add a new series using existing series
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [50]:
data.iloc[1,2]

114.80612053173

In [53]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [54]:
# Masking
data.loc[data.density > 100, ['pop', 'density']]

pop     density
Florida   19552860  114.806121
New York  19651127  139.076746

In [55]:
data[1:3]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [56]:
data[data.density > 100]

area       pop     density
Florida   170312  19552860  114.806121
New York  141297  19651127  139.076746

## Handling Missing Data

In [57]:
data = pd.Series([1, np.nan, 'hello', None])

In [58]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [59]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [60]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [61]:
data.dropna()

0        1
2    hello
dtype: object

## Pandas MultiIndex

In [63]:
# define index as a list of tuples
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
index

[('California', 2000),
 ('California', 2010),
 ('New York', 2000),
 ('New York', 2010),
 ('Texas', 2000),
 ('Texas', 2010)]

In [64]:
# now redefine as a multiindex
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [67]:
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [68]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [70]:
pop_df['total']

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
Name: total, dtype: int64

In [73]:
pop_df.iloc[0]

total      33871648
under18     9267089
Name: (California, 2000), dtype: int64

In [74]:
pop_df.iloc[1]

total      37253956
under18     9284094
Name: (California, 2010), dtype: int64

In [75]:
pop_df.loc['California']

total  under18
2000  33871648  9267089
2010  37253956  9284094

In [77]:
pop_df.loc['Texas']

total  under18
2000  20851820  5906301
2010  25145561  6879014

In [79]:
pop[:,2000]

California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [80]:
pop[pop > 22000000]

California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64