In [1]:
import numpy as np
import pandas as pd

In [5]:
# Python list
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
# slice syntax: [i:j] - elements i, i+1, ..., j-1
# missing values -- wildcard (everything)
a[3:7]

[3, 4, 5, 6]

In [6]:
a[:4]

[0, 1, 2, 3]

In [8]:
a[8:]

[8, 9]

In [11]:
# Numpy array
y = np.array(range(25)).reshape(5, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [12]:
# the same slice expression as Python lists -- i:j along each axis
x = y[2:, 2:]
print(x)

[[12 13 14]
 [17 18 19]
 [22 23 24]]


In [13]:
z = y[:2, :2]
print(z)

[[0 1]
 [5 6]]


In [14]:
print(y[:, 1:-1])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]]


In [17]:
# Pandas
df = pd.read_csv("../data/08_2012_Annual_Report_to_Congress_on_White_House_Staff.csv")
df.head(10)

Name    Status    Salary  Pay Basis  \
0    Aberger, Marie E.  Employee   42000.0  Per Annum   
1     Abrevaya, Sandra  Employee   90000.0  Per Annum   
2      Agnew, David P.  Employee  153500.0  Per Annum   
3     Ahmed, Rumana A.  Employee   42565.0  Per Annum   
4        Albino, James  Employee   93000.0  Per Annum   
5     Alcantara, Elias  Employee   42000.0  Per Annum   
6  Anderson, Amanda D.  Employee  102000.0  Per Annum   
7   Anello, Russell M.  Detailee   92001.0  Per Annum   
8   Arguelles, Adam J.  Employee  102000.0  Per Annum   
9  Aron-Dine, Aviva R.  Employee  130500.0  Per Annum   

                                      Position Title  
0                                    PRESS ASSISTANT  
1                  ASSOCIATE COMMUNICATIONS DIRECTOR  
2  DEPUTY ASSISTANT TO THE PRESIDENT AND DIRECTOR...  
3  EXECUTIVE ASSISTANT TO THE DIRECTOR OF PUBLIC ...  
4                             SENIOR PROGRAM MANAGER  
5                                    STAFF ASSISTANT  
6  SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLA...  
7                                  ASSISTANT COUNSEL  
8  SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLA...  
9  SPECIAL ASSISTANT TO THE PRESIDENT FOR ECONOMI...

In [18]:
# the iloc[i:j] method is similar to list and NumPy array slicing
df.iloc[3:7]

Name    Status    Salary  Pay Basis  \
3     Ahmed, Rumana A.  Employee   42565.0  Per Annum   
4        Albino, James  Employee   93000.0  Per Annum   
5     Alcantara, Elias  Employee   42000.0  Per Annum   
6  Anderson, Amanda D.  Employee  102000.0  Per Annum   

                                      Position Title  
3  EXECUTIVE ASSISTANT TO THE DIRECTOR OF PUBLIC ...  
4                             SENIOR PROGRAM MANAGER  
5                                    STAFF ASSISTANT  
6  SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLA...

In [20]:
df.iloc[3:7, 1:3]

Status    Salary
3  Employee   42565.0
4  Employee   93000.0
5  Employee   42000.0
6  Employee  102000.0

In [21]:
# Note that loc[] uses the row names.  If the names are integers, slicing
# looks similar, but df.loc[i:j] includes rows i, i+1, ... AND j.
df.loc[3:7]

Name    Status    Salary  Pay Basis  \
3     Ahmed, Rumana A.  Employee   42565.0  Per Annum   
4        Albino, James  Employee   93000.0  Per Annum   
5     Alcantara, Elias  Employee   42000.0  Per Annum   
6  Anderson, Amanda D.  Employee  102000.0  Per Annum   
7   Anello, Russell M.  Detailee   92001.0  Per Annum   

                                      Position Title  
3  EXECUTIVE ASSISTANT TO THE DIRECTOR OF PUBLIC ...  
4                             SENIOR PROGRAM MANAGER  
5                                    STAFF ASSISTANT  
6  SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLA...  
7                                  ASSISTANT COUNSEL