# In Class Work 1
This notebook will store the in class work that I do.

Some LaTeX: $\sum_{n=1}^{10}2^{-n}$ (just to show that LaTex is rendered in markdown)

In [ ]:
print ("Hello World!")

In [ ]:
for j in range(20):
    print ("[{:2d}] Hello World.".format(j))

In [ ]:
import numpy as np
rolls = np.random.randint(1, 7, 1000)
[list(rolls).count(j) for j in range(1, 7)]

In [ ]:
"Average: {:.3f}; Std. Dev.: {:.3f}".format(np.mean(rolls), np.std(rolls))

In [ ]:
L = [1, 2, 42, 55, 1, 1, 2, 3, 4, 5, 96, 19, 22, 78, 17, 78, 2, 2, 2, 5, 14, 90, 96, 96, 97]

In [ ]:
d = {}
for j in L:
    if j in d:
        d[j] = d[j] + 1
    else:
        d[j] = 1
d

In [ ]:
# the ternary if version that I didn't get to in class
d = {}
for j in L:
    d[j] = d[j] + 1 if j in d else 1
d

In [ ]:
list(d.keys())

In [ ]:
[k for k in d if d[k] > 1]

In [ ]:
list(set(L))

## slicing examples

In [1]:
import numpy as np
def show(the_array, show_data = 0):
    print("  Dimension: {:}".format(the_array.ndim))
    print("       Size: {:}".format(the_array.size))
    print("      Shape: {:}".format(the_array.shape))    
    print("  Data Type: {:}".format(the_array.dtype))    
    print("  Item Size: {:}".format(the_array.itemsize))
    print("Data Buffer: {:}".format(the_array.data))
    if show_data:
        print(the_array)
x = np.array(range(10))
show(x, 1)

  Dimension: 1
       Size: 10
      Shape: (10,)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x000001DD16D6E348>
[0 1 2 3 4 5 6 7 8 9]


In [2]:
y = np.array(range(25)).reshape(5, 5)
show(y, 1)

  Dimension: 2
       Size: 25
      Shape: (5, 5)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x0000019B750E2048>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [17]:
a = x[:8].copy()
a[2] = 1673

In [18]:
a, x


(array([   0,    1, 1673,    3,    4,    5,    6,    7]),
 array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9]))

In [19]:
b = y[1:, -1:]

In [20]:
y, b

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]), array([[ 9],
        [14],
        [19],
        [24]]))

In [2]:
# What I was trying to in class but couldn't -- slice the "middle" of the array
y = np.array(range(25)).reshape(5, 5)
show(y, 1)

  Dimension: 2
       Size: 25
      Shape: (5, 5)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x000001DD16DD3048>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
#It's so simple when you're not under presssure!
y[1:-1,1:-1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])