# Question about NumPy Array Shape/Dimensions
Submitted by Dan O'Leary, Fall 2018

This is an awesome question -- I spent quite a while on this one myself when I was learning the details of arrays.

In [4]:
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [5]:
a.shape

(3,)

This result is a bit surprising. I would expect (1,3) for one row, three columns, or maybe (,3) for zero rows, three columns, or simply (3). But (3,) doesn't seem logical.
Let's try a 2d array and compare results...

In [6]:
M = np.ones((3,2))
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Note the subtle difference in notation between the output of a, which has single square brackets, and M, which has double square brackets. 

In [7]:
M.shape

(3, 2)

This is what I would expect for three rows, two columns.

In [8]:
a[: , np.newaxis]

array([[0],
       [1],
       [2]])

After this transformation, a also uses the double bracket notation...

In [9]:
a[: , np.newaxis].shape

(3, 1)

In [10]:
# flip the new axis around
a[np.newaxis, :]

array([[0, 1, 2]])

In [11]:
a[np.newaxis, :].shape

(1, 3)

And its shape is what I would expect - three rows, one column. I see the difference, but expect I'm not alone in overlooking the distinction between [ [ ] ] for 2d+ data and [ ] for 1d data. Even understanding it now, I remain a bit perplexed by the (3,) result for a.shape.

In [12]:
# My response - the confusion is with the dimensionality of the arrays (combined with the 
# weirdness of the shape display for a 1-d array)
# Consider this example
a1 = np.arange(3)
a2 = np.arange(3).reshape(3, 1)
a3 = np.arange(3).reshape(1, 3)

In [13]:
a1

array([0, 1, 2])

In [14]:
a2

array([[0],
       [1],
       [2]])

In [15]:
a3

array([[0, 1, 2]])

In [16]:
a1.shape, a2.shape, a3.shape

((3,), (3, 1), (1, 3))

In [17]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 2)

So, a1 is a 1-dimensional array while a2 and a3 are 2-dimensional arrays (even though one of their dimensions only has a single element).

When you used the np.newaxis parameter, you were "stretching the 1-d array" -- vertically in the first case (yours) and horizontally in the second (my addition).

I googled "why does the shape attribute for a 1-dimensional numpy array have a trailing comma?" and got the following from (https://stackoverflow.com/questions/46134891/why-an-extra-comma-in-the-shape-of-a-single-index-numpy-array):

The reason we don't use (12) for a one-element tuple (like [12] for one-element list) is that round parentheses also appear in formulas. E.g., in x = 2*(5+7) the part (5+7) is just a number, not a tuple. But what if we actually meant it to be a one-element tuple? The trailing comma is a way to indicate that. 
